"""Read-only copilot context; numerical evidence is never generated by an LLM."""

from sqlalchemy import select

from apps.api.db import District, PHC
from apps.api.domain import facility, inventory_forecast, recommend, warm_resources


def gather(session, pid, question, language):
    cache = session.info.get("resources")
    if not cache:
        warm_resources(session, "ors")
        cache = session.info.get("resources", {})
    phc = cache.get("facilities", {}).get(pid) or session.get(PHC, pid)
    plan = recommend(session, pid, "ors", persist=False)
    f = inventory_forecast(session, pid, "ors")
    district = cache.get("districts", {}).get(phc.district_id) or session.get(District, phc.district_id)
    facilities = list(cache.get("facilities", {}).values()) or session.scalars(select(PHC)).all()
    region = [
        facility(session, p)
        for p in facilities if p.district_id == district.id
    ]
    ranked = sorted(region, key=lambda p: -p["ors"]["risk"])
    evidence = {
        "facility": {"name": phc.name, "id": pid},
        "forecast": f,
        "plan": plan,
        "district": {
            "name": district.name,
            "facilities": len(region),
            "high_risk_ors": sum(p["ors"]["risk"] > 0.7 for p in region),
            "available_beds": sum(p["beds"]["available"] for p in region),
            "daily_footfall": round(sum(p["capacity"]["predicted_footfall"] for p in region)),
            "priority": [
                {
                    "name": p["name"],
                    "risk": p["ors"]["risk"],
                    "truth_score": p["ors"]["truth"]["score"],
                }
                for p in ranked[:5]
            ],
        },
    }
    summary = f"{phc.name}: ORS usable stock {f['usable']}; predicted demand {f['daily_demand']:.1f}/day; {f['days_cover']:.1f} days of cover. Seven-day shortage risk {plan['risk_before']:.1%}. Data TruthScore {f['truth']['score']}/100; forecast confidence {f['forecast_confidence']}%."
    q = question.lower()
    if "district" in q or "summar" in q:
        d = evidence["district"]
        summary = (
            f"{d['name']} district: {d['facilities']} PHCs, {d['high_risk_ors']} with ORS risk above 70%, {d['available_beds']} available beds, and {d['daily_footfall']} predicted patients/day. "
            + summary
        )
    if any(word in q for word in ["first", "priorit", "intervention"]):
        summary += (
            " District ORS risk ranking: "
            + "; ".join(
                f"{p['name']} ({p['risk']:.1%}, TruthScore {p['truth_score']})"
                for p in evidence["district"]["priority"]
            )
            + "."
        )
    if any(
        word in q
        for word in [
            "closest",
            "closer",
            "nearest",
            "donor",
            "transfer",
            "redistribut",
            "recommend",
        ]
    ):
        if plan["rejected"]:
            rejected = plan["rejected"][0]
            summary += f" {rejected['name']}: a full {rejected['naive_quantity']}-unit transfer would produce {rejected['naive_risk']:.1%} donor risk. {rejected['reason']}. Safe contribution: {rejected['safe_quantity']}."
        summary += (
            " Proposed contributions: "
            + (
                "; ".join(
                    f"{d['name']} → {d['quantity']} units; donor risk {d['risk_before']:.1%} → {d['risk_after']:.1%}"
                    for d in plan["donors"]
                )
                or "none available"
            )
            + "."
        )
    summary += f" Proposed recipient risk after arrival: {plan['risk_after']:.1%}; unfilled quantity: {plan['unfilled']}. Synthetic decision support only; officer approval is required."
    if language == "Telugu":
        summary = (
            f"{phc.name}: ఉపయోగించగల ORS నిల్వ {f['usable']} యూనిట్లు. అంచనా రోజువారీ అవసరం {f['daily_demand']:.1f}. నిల్వ {f['days_cover']:.1f} రోజులకు సరిపోతుంది. ఏడు రోజులలో కొరత ప్రమాదం {plan['risk_before']:.1%}. డేటా TruthScore {f['truth']['score']}/100. అంచనా విశ్వాసం {f['forecast_confidence']}%. ప్రతిపాదిత బదిలీ తర్వాత ప్రమాదం {plan['risk_after']:.1%}. అధికారి ఆమోదం అవసరం. ఇవి కృత్రిమ డేటా ఆధారిత అంచనాలు.\n\nEnglish evidence:\n"
            + summary
        )
    return evidence, summary
